version: "3"
services:
  nats:
    container_name: "nats_core"
    image: nats
    ports:
      - "8222:8222"
      - "6222:6222"
      - "4222:4222"
    networks:
      - nats_test
  nats-streaming:
    container_name: nats-streaming
    image: nats-streaming
    ports:
      - "4223:4222"
      - "8223:8222"
    networks:
      - nats_test


networks:
  nats_test:
    driver: bridge